version: '3.6'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
      - mongo-data:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users

volumes:
  mongo-data:
    name: users-mongo-data
